Development
AlejoCode/RubyEnumerableMethods pull request #1
Opened 2019-07-23 00:38 UTC by AlejoCode

Please check my methods to see if they are done correctly I will be waiting any response for you guys thank you so much and have a great day :D

2019-07-23 01:38 UTC, bellom commented
## Currently reviewing this PR

2019-07-23 02:15 UTC, bellom requested changes
Hi @AlejoCode, 

Great work, all methods working just few things to do and have your :+1: .

To consider the project 'complete' it must satisfy the following Microverse guidelines key points; 
*  [ ]  The project has a descriptive README.md
*  [ ]  Make sure that code is clean: indentation with two spaces, line lengths, spaces around operators - first section of [this link](https://github.com/github/rubocop-github/blob/master/STYLEGUIDE.md#ruby-style-guide).

Kindly correct these few things and submit another code review.....

2019-07-25 00:52 UTC, bellom commented
## Currenly reviewing this PR

2019-07-25 01:32 UTC, bellom requested changes
Hi @AlejoCode, 
#### Waited for more than 30 mins hoping to get a response from you.
_Free to messages me on slack if you need help or anything you don't understand._
**_kindly make the changes i mentioned in my first review and re-submit another code review._**

2019-07-25 01:32 UTC, bellom commented on enumerable.rb
> +      i+=1
space should be around operator

2019-07-25 01:32 UTC, bellom commented on enumerable.rb
> +      i+=1
space should be around operator

2019-07-25 01:32 UTC, bellom commented on enumerable.rb
> +  def my_map proc=nil
space should be around operator

2019-07-26 01:18 UTC, AdnanAfsari commented
Adnan Afsari working on it :)

2019-07-26 02:17 UTC, AdnanAfsari commented
Hello @AlejoCode 

Your project should have README.md and it should be well documented to get approval :)

Please submit for another review after making the change.

Happy Coding

2019-07-29 17:50 UTC, JamesOkunlade commented
James working on it.

2019-07-29 17:55 UTC, JamesOkunlade approved these changes
You have added an updated README.md as requested by the previous reviewer.

It's a :+1: from me. Merge to master, close pull request and fill the project completion form.

Good luck with your future projects.

2019-08-02 01:57 UTC, merged